language: node_js
sudo: false

node_js:
  # Node.js 0.10 and 0.12 are not supported.
  #- "0.10"
  #- "0.12"
  - "4"
  - "5"

after_success:
  - npm run coverage
  - npm i coveralls
  - cat ./coverage/lcov.info | coveralls

notifications:
  email:
    on_success: never
